### PR TITLE
Added more translations

### PR DESCRIPTION
**Pull request by stefonarch**
Includes also the[ .ts file for croatian](https://github.com/lxqt/sddm-config-editor/pull/29)  and its changes needed.

### CODE REVIEW

**Comment by stefonarch** [comment]
Closes also https://github.com/lxqt/sddm-config-editor/issues/21

**Comment by yan12125** [comment]
Among new files, only hr, it, ru have non-empty translations. Is there a reason to add languages without translations?

By the way, CMake seems the future for the C++ part of sddm-config-editor - https://github.com/lxqt/sddm-config-editor/issues/20. Please also modify `CMakeLists.txt`.

**Comment by stefonarch** [comment]
Croatian (hr) is new, pt is done now in `https://translate.lxqt-project.org/projects/lxqt-configuration/sddm-config-editor/` and hebrew partly. I added just the most common languages.

I always compiled using ` qmake && make` in cpp as stated in cpp/README.md

The usual
   `mkdir build && cd build && cmake ..  -DCMAKE_INSTALL_PREFIX=/usr  -DCMAKE_BUILD_TYPE=Debug && make -j4`

works as well but language is not included then, turns back to english here.

**Comment by yan12125** [comment]
> Croatian (hr) is new, pt is done now in https://translate.lxqt-project.org/projects/lxqt-configuration/sddm-config-editor/ and hebrew partly.

Oh got it. But I think Weblate will create `*.ts` files when necessary? That is also what I see in `~/data/vcs/lxqt-configuration/sddm-config-editor` on translate.lxqt-project.org.

> works as well but language is not included then, turns back to english here.

<del>I guess things will work after https://github.com/lxqt/sddm-config-editor/blob/master/CMakeLists.txt#L25-L29 is updated?</del> Sorry didn't notice you already did that. Will check what goes on in cmake.

Another point: if you want to include Croatian translations in this PR, please add `Co-authored-by: milotype <43657314+milotype@users.noreply.github.com>` to preserve credits.

**Comment by stefonarch** [comment]
>  But I think Weblate will create `*.ts` files when necessary?

Yes, and if this happens we have to update all those files again, that's the reason why I added already some empty files now to cover most common languages. 

> Co-authored-by: milotype ....

done hopefully

**Comment by yan12125** [comment]
> Will check what goes on in cmake.

I can confirm translations do not work with cmake. Left a comment in #20.

> done hopefully

Somehow GitHub does not recognize that line if the second line in the commit message is not a blank line. I fixed that.

I think everything other than the cmake issue is fixed - gonna merge. Thanks for the work!

**Comment by yan12125** [comment]
Sorry, but I have no idea how to fix so many conflicts between this pull request and commits from weblate, so I take a different route - revert this pull request in #32, merge the Croatian translation in #29 and weblate commits in #31. For remaining parts of this pull request (updating project files and .desktop), please open another pull request.

**Comment by stefonarch** [comment]
Made a new PR https://github.com/lxqt/sddm-config-editor/pull/33 including also hebrew and the clean .desktop file.

**Pull request merged**
