### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by LXQtBot**
Translations update from [Weblate](https://translate.lxqt-project.org/projects/lxqt-configuration/sddm-config-editor/) for LXQt Configuration/sddm-config-editor.

### CODE REVIEW

**Comment by yan12125** [comment]
@stefonarch Any idea why the second commit uses https://translate.lxqt-project.org/projects/lxqt-configuration/pavucontrol-qt/?

**Comment by stefonarch** [comment]
Oops, looks like a copy&paste error, found jiust another one in pavucontrol-qt.
Should I just make  another commit or is there a better way?  

Anyway, new translations here will only work if [this PR](https://github.com/lxqt/sddm-config-editor/pull/30) is merged.

**Comment by yan12125** [comment]
> Should I just make another commit or is there a better way?

I'm not sure how weblate handles README.md commits. Do whatever you want that brings correct results :)

> Anyway, new translations here will only work if this PR is merged.

Thanks for the reminder. Looks like this will be a draft for some time.

**Comment by stefonarch** [comment]
> Thanks for the reminder. Looks like this will be a draft for some time.

I see weblate and the bot do a force-push. 
Is this repository kind of orphan? The editor has always worked well for me, and I would not consider it "early alpha".

**Pull request merged**
