### PR TITLE
updated translation-relevant files and .desktop file

### PR DESCRIPTION
**Pull request by stefonarch**
Added also hebrew that's 15%done in weblate.

### CODE REVIEW

**Comment by yan12125** [comment]
With #35, CMake can discover translation sources automatically. For `translations.qrc` and `sddm-config-editor.pro` - I think it's time to remove them as the CMake build system is now fully functional.

**Comment by stefonarch** [comment]
Will make a new PR after some testing.

**Comment by stefonarch** [comment]
Well, rebase failure as usual when  language relevant commit are merged after some time without locking  translations before the comit branch is created.

**Comment by yan12125** [comment]
Unfortunately git is sometimes not as clever as humans lol

**Pull request closed without merging**
